name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_URL: ${{ secrets.APP_URL }}
      VERCEL_URL: ${{ secrets.VERCEL_URL }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar tipos
        run: npm run typecheck || npm run check-types || true

      - name: Executar linter
        run: npm run lint

      - name: Executar testes
        run: npm run test || true

      - name: Build do projeto
        run: npm run build